### PR TITLE
WIP: Update to Shard v3

### PR DESCRIPTION
**Pull request by joshystuart**
_Do not merge_

This is a work in progress PR so we can discuss.

### CODE REVIEW

**Comment by joshystuart** [comment]
@superdweebie I need some help with this one. There's a lot of errors I'm working through. Are you able to pull and run `phpunit` to see some of the problems? Thanks in advance.

**Comment by superdweebie** [comment]
@crimsonronin I'll get a little time to work on this tonight, and then quite a bit tomorrow. I'll keep you updated.

**Comment by joshystuart** [comment]
Thanks! I could work through them, albeit slowly! I'm sure you have some insights that would speed things along.

**Comment by superdweebie** [comment]
I'm on this. It's been a little while since I've done solid php stuff at home, so I ended up spending the evening rebuilding my dev environment - update java, update netbeans, update php, update mongo driver, update composer, install gateway-module and all deps. It's all working now, but there has to be a simpler way!

I'll debug some actual code tomorrow

**Comment by joshystuart** [comment]
haha. That sounds tedious! All good.

**Comment by joshystuart** [comment]
Hey @superdweebie,

How's this going? Any luck?

**Comment by superdweebie** [comment]
@crimsonronin sorry about the silence. I've got gateway up and running with the latest shard. I've also looked over gomi, and it looks good. I'll push it all up tonight.

**Comment by joshystuart** [comment]
Beautiful @superdweebie! Very keen to get my hands on it! Thanks again.

So the work I did on gomi was ok then?

**Comment by superdweebie** [comment]
Yes, your work on gomi was great. I just added phpmd to the travis file, and cut out a little dead code (left over from me). I have hit a small snag with shard, which I have almost resolved. Detailed here: https://github.com/zoopcommerce/shard/issues/59

**Comment by joshystuart** [comment]
Sounds good.

**Comment by superdweebie** [comment]
Closing. Handled by #2

**Pull request closed without merging**
